### ISSUE TITLE
Profile switching fails

### ISSUE THREAD

**Issue by karljs** [terrymacdonald/DisplayMagician#316]
**Describe the bug**

I have 3 screens total  (2 LG, 1 Samsung which makes me wonder if https://github.com/terrymacdonald/DisplayMagician/issues/312 could possible be the same issue).  I tried to set up 2 profiles, one that uses a single screen and another that uses the other 2.  Switching between them causes some activity on the monitors (various LEDs blink, they come to life if asleep) but ultimately the actual display configuration is not switched over and it reverts to the previous setting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create two profiles
2. Be in profile 1 and apply profile 2, note that nothing happens and screen configuration appears as if in profile 1
3. Apply profile 1 again, the screen flashes, and remains in the same profile 1 configuration it's been in the whole time.

**Expected behaviour**

**Screenshots**

**Reporting Logs**
[DisplayMagician-Support-20240626-1225.zip](https://github.com/user-attachments/files/15994381/DisplayMagician-Support-20240626-1225.zip)
[DisplayMagician(1).log](https://github.com/user-attachments/files/15994576/DisplayMagician.1.log)

**Enviroment (please complete the following information):**
 - Windows Version: Win11
 - DisplayMagician Version: 2.5.0.352
 - Video Card: NVidia RTX 3090
 - Number and make/model of monitors:
    1. 2x LG 27GN950
    2. Samsung Odyssey G95NC
 - Date of last video driver update: 2024-06-04
 - Date of last windows update: 2024-06-26
**Additional context**

**Comment by terrymacdonald** [comment]
Hi @karljs,

Hmmmm. I can't really see anything in the logs specifically, other than one of your monitors is being detected as a 0x0 sized screen. I can't tell why this is being detected this way though unfortunately. I'll try looking through your config in more detail when I get a chance.

I also can't tell if its related to #316, as the person who logged that hasn't provided any logs, making troubleshooting impossible.

Another avenue you can try to to test the new pre-alpha version of DisplayMagician v2.6.0.38073 which I just released last night. It fixes a lot of bugs, and some of those fixes may help your situation. Please be warned though - it uses a new file format, and I'm currently still adjusting the file format, so you will NEED to recreate your DM config from  scratch, and you will NEED to do it again when I release the final version of DM v2.6.0.

You can get the latest pre-alpha DM from here:  [DisplayMagicianSetup-v2.6.0.38073.zip](https://github.com/user-attachments/files/16043856/DisplayMagicianSetup-v2.6.0.38073.zip)

Thanks
Terry

**Comment by karljs** [comment]
Thanks for taking a look.  Unfortunately that pre-alpha version doesn't fix my issue.  I've included a new log just in case there are any changes that might make it more helpful, but I guess for now I'll have to do this the hard way.
[DisplayMagician-2024-06-30-2155.log](https://github.com/user-attachments/files/16048079/DisplayMagician-2024-06-30-2155.log)

**Comment by karljs** [comment]
Small anecdote that might be helpful as a direction: I tried using _Monitor Profile Switcher_ as an alternative and it had the same problem.  However, what I noticed is that if I switch my profile a second time in quick succession with that tool, it works the second time.  So it seems it has something to do with the monitor not being fully woken up on the first attempt.  DisplayMagician doesn't let me switch to the same profile repeatedly (which admittedly doesn't make sense under normal circumstances) so I can't try it.

**Comment by terrymacdonald** [comment]
Hi Karl,

Sounds like it could be either the hardware, or the NVIDIA driver to me
based on what you're describing. If it's happening with Monitor Profile
Switcher then that calls the same NVIDIA NvAPI and Windows CCD API calls
that I use. This effectively eliminates DisplayMagician from being the
problem.

In order to nail down what the issue is, you could try NVIDIAInfo.
NVIDIAInfo is a small program that I wrote to test out the NVIDIALibrary
that I wrote. I've recently found some bugs with it, and I've been
trialling some new tests after copying code from Soroush Falahati's
awesome NVAPIWrapper ..net project. So you could do some testing using that
as it may help point to where the problem lies.

You can get the latest test NVIDIAInfo from here:
https://github.com/user-attachments/files/16048338/NVIDIAInfo-v2.0.0-alphatest.zip

Instructions on how to use the application are here:
https://github.com/terrymacdonald/NVIDIAInfo/releases

This should allow you to apply the same config twice to see if that works
or not. This also uses a completely new NVIDIALibrary, so that might
possibly help things. My gut feel though is that it's something hardware or
driver related, in which NVIDIAInfo won't help.

Thanks

*Terry *

**Comment by terrymacdonald** [comment]
Weirdly, I've got another user who is having issues with a Samsung Odyssey screen showing up as a 0x0 screen as well. I wonder if there is a hardware issue with Samsung Odyssey monitors? I'll have to do some more digging.

**Comment by Park0h** [comment]
> Weirdly, I've got another user who is having issues with a Samsung Odyssey screen showing up as a 0x0 screen as well. I wonder if there is a hardware issue with Samsung Odyssey monitors? I'll have to do some more digging.

Hi, It seems I also may have this problem. any updates on why this could be happening?

**Comment by chris023** [comment]
I've got the same issue using an earlier model Odyssey G9.  Switching back to the G9 from my rig triples fails the first time, but succeeds on the second attempt as long as I leave DisplayMagician open between attempts.  Trying to switch using a generated .lnk fails indefinitely.  The G9 has issues waking from sleep, I had to upgrade my firmware on the monitor a year or two ago to get it to start waking up from sleep consistently. Possibly related to that issue

**Comment by chris023** [comment]
Here's my workaround in an ahk2 script that lets me switch profiles with one button press still 
![image](https://github.com/user-attachments/assets/63b0801f-3fc9-4d4b-8e73-8d156cc3e08e)

**Comment by terrymacdonald** [comment]
Okay team. I've had a little think about this, and I'm in the process of building the ability for you all to apply a profile multiple times with a user configurable delay between the attempts. This is to specifically work around the problems with the Samsung Odyssey display you are all having. 

I have the code creating the profile working and it works when it applies the display profile. My next step is to build the UI for it, and then I'll drop a new test release for you all to test out. I'm hoping this works around the problems that this display has caused you all, and makes life happy again.

It'll be a few days before I can get the code locked down and working. Please bear with me.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Ok! The release 2.7.2.26 contains the ability to apply a display profile multiple times. To keep track of where i am up to, I've closed this issue as I know I've written code for it.

@karljs @Park0h @chris023 can you please all test this one out? https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.2.26

You will find the new settings by going Main Window > Display Profiles > Profile Settings and there you will find a selector to let you pick the number of times you can apply the Display Profile, and the number of seconds to wait between applying the Display Profile again. The default is of course to apply a Display Profile once.

Please note that any saved Display Profiles can be adjusted to apply display layouts more than once, but be aware that if you are using a Game Shortcut to apply a saved Display Profile, when DM reverts back to the previous 'in-use' display layout, that display layout is applied only once. There is no way to apply the previous 'in-use' display layout multiple times at present.

Hopefully what I've built provides enough flexibility to get those darn Samsung G95 displays to apply their settings properly!

Thanks
Terry

**Comment by karljs** [comment]
@terrymacdonald Sorry for the extremely slow response.  This solves my problem, thanks for taking the time to look into it.
